### ISSUE TITLE
vmware_rest: ansible.content_builder generates lots of unused import

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/ansible.content_builder#67]
##### SUMMARY
It looks like ansible.content_builder generates lots of unused imports in [vmware.vmware_rest](https://github.com/ansible-collections/vmware.vmware_rest).

There's #58 but I don't consider this a real fix. I guess there are good reasons for this sanity test... so I would suggest to

1. _Not_ generate all those unused imports or, if this would be too hard to implement
2. _Remove_ them again in a second step; [autoflake](https://pypi.org/project/autoflake/) seems to be able to do this, but there might be other (and possibly better) solutions to achieve this

##### ISSUE TYPE
- Bug Report

##### EXPECTED RESULTS
No unused imports.

##### ACTUAL RESULTS
Hundreds of unused imports.

**Comment by mariolenz** [comment]
@GomathiselviS I've just seen your comments in ansible-collections/vmware.vmware_rest#416 and it looks like it would be too complicated to not generate unused imports.

However, I've fixed the sanity errors in ansible-collections/vmware.vmware_rest#432 by removing the unused imports with [autoflake](https://pypi.org/project/autoflake/). This was quite simple. Would it be possible to automatically run autoflake on the generated files as a final step? This would fix the sanity tests without having to ignore them.

@abikouo @alinabuzachis You've said in ansible-collections/vmware.vmware_rest#416 that you would rather prefer the generator to import only required modules and not ignore the tests. What do you think of my proposal? The generator would still create unused imports but they would be removed in a final step.

**Comment by GomathiselviS** [comment]
@mariolenz I have added a task to run autoflake on the generated modules [here](https://github.com/ansible-community/ansible.content_builder/pull/70). Please review.

**Comment by mariolenz** [comment]
resolved_by #70
